include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore

linter:
  rules:
    unnecessary_this: false
    always_declare_return_types: true
    camel_case_types: true
    empty_constructor_bodies: true
    annotate_overrides: true
    avoid_init_to_null: true
    constant_identifier_names: true
    one_member_abstracts: true
    slash_for_doc_comments: true
    cancel_subscriptions: true
    close_sinks: true
    unnecessary_const: true
    unnecessary_new: true
    prefer_single_quotes: true
    require_trailing_commas: true
